# Generated by Django 6.0.3 on 2026-06-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sozlesme', '0007_alter_sozlesmeler_sozlesmeno_alter_sozlesmeler_tanim'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasrafTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=100, unique=True, verbose_name='Masraf Türü')),
            ],
            options={
                'verbose_name': 'Masraf Türü',
                'verbose_name_plural': 'Masraf Türleri',
            },
        ),
        migrations.CreateModel(
            name='Masraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muhatap_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Muhatap Adı')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('fis_no', models.CharField(max_length=50, verbose_name='Fiş No')),
                ('aciklama', models.CharField(max_length=60, verbose_name='Açıklama')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('para_birimi', models.CharField(choices=[('TRY', 'TRY'), ('EUR', 'EUR'), ('USD', 'USD')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('odendi_mi', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sozlesme.sozlesmeler', verbose_name='Sözleşme')),
                ('masraf_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masraf.masrafturu', verbose_name='Masraf Türü')),
            ],
            options={
                'verbose_name': 'Masraf',
                'verbose_name_plural': 'Masraflar',
            },
        ),
    ]
