# Generated by Django 6.0.3 on 2026-06-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masraf', '0001_initial'),
        ('muhatap', '0010_muhatap_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='masrafturu',
            name='muhatap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masraf_turleri', to='muhatap.muhatap', verbose_name='Firmaya Özel (Boş = Genel)'),
        ),
        migrations.AlterField(
            model_name='masrafturu',
            name='tanim',
            field=models.CharField(max_length=100, verbose_name='Masraf Türü'),
        ),
        migrations.AlterUniqueTogether(
            name='masrafturu',
            unique_together={('tanim', 'muhatap')},
        ),
    ]
