# Generated by Django 6.0.3 on 2026-06-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masraf', '0002_masrafturu_muhatap_fk'),
        ('modul', '0008_bolum_yazilim_eforuna_dahil'),
        ('proje', '0003_projeler_aciklama_alter_projeler_tanim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masraf',
            name='sozlesme',
        ),
        migrations.AddField(
            model_name='masraf',
            name='danisman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modul.danisman', verbose_name='Danışman'),
        ),
        migrations.AddField(
            model_name='masraf',
            name='proje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proje.projeler', verbose_name='Proje'),
        ),
    ]
