# Generated by Django 6.0.3 on 2026-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masraf', '0003_remove_masraf_sozlesme_masraf_danisman_masraf_proje'),
    ]

    operations = [
        migrations.AddField(
            model_name='masraf',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='masraf_dosyalari/', verbose_name='Dosya (PDF/Resim)'),
        ),
    ]
