# Generated by Django 6.0.2 on 2026-02-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muhatap', '0010_muhatap_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='sozlesmeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesmeno', models.CharField(default='2026-', unique=True)),
                ('tanım', models.CharField()),
                ('muhatap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muhatap.muhatap', to_field='unvan')),
            ],
        ),
    ]
