# Generated by Django 6.0.2 on 2026-02-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sozlesmeler',
            old_name='tanım',
            new_name='tanim',
        ),
    ]
