# Generated by Django 6.0.2 on 2026-02-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0002_rename_tanım_sozlesmeler_tanim'),
    ]

    operations = [
        migrations.CreateModel(
            name='sozlesmetip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=100)),
            ],
        ),
    ]
