# Generated by Django 6.0.2 on 2026-02-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0003_sozlesmetip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesmeler',
            name='baslangic_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sozlesmeler',
            name='bitis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sozlesmeler',
            name='tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sozlesme.sozlesmetip', to_field='tanim'),
        ),
        migrations.AlterField(
            model_name='sozlesmetip',
            name='tanim',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
