# Generated by Django 6.0.2 on 2026-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0004_sozlesmeler_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesmeler',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
