# Generated by Django 6.0.2 on 2026-03-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0005_sozlesmeler_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='projelist',
            fields=[
                ('projeno', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('projetanim', models.CharField(max_length=100)),
                ('sozlesmeno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sozlesme.sozlesmeler', to_field='sozlesmeno')),
            ],
        ),
    ]
