# Generated by Django 6.0.3 on 2026-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0006_projelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozlesmeler',
            name='sozlesmeno',
            field=models.CharField(default='2026-', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sozlesmeler',
            name='tanim',
            field=models.CharField(max_length=200),
        ),
    ]
