# Generated by Django 6.0.3 on 2026-05-25 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modul', '0007_danisman_email_danisman_tur'),
        ('muhatap', '0010_muhatap_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Firma', 'Firma (Müşteri)'), ('Danisman', 'Danışman')], default='Admin', max_length=20)),
                ('is_approved', models.BooleanField(default=True)),
                ('get_danisman_profiller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modul.danisman', to_field='username')),
                ('get_muhatap_firmalar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhatap.muhatap', to_field='unvan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
