# Generated by Django 6.0.3 on 2026-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0008_bolum_yazilim_eforuna_dahil'),
        ('muhatap', '0010_muhatap_slug'),
        ('uyelik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='danisman_profiller',
            field=models.ManyToManyField(blank=True, related_name='kullanici_profilleri_coklu', to='modul.danisman'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='muhatap_firmalar',
            field=models.ManyToManyField(blank=True, related_name='kullanici_profilleri_coklu', to='muhatap.muhatap'),
        ),
    ]
