# Generated by Django 6.0.3 on 2026-06-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uyelik', '0002_userprofile_danisman_profiller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='get_danisman_profiller',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='get_muhatap_firmalar',
        ),
    ]
