# Generated by Django 6.0.2 on 2026-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destekturu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destektur',
            name='definition',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
