# Generated by Django 6.0.2 on 2026-02-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destekturu', '0002_alter_destektur_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='oncelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=3)),
                ('tanim', models.CharField(max_length=100)),
            ],
        ),
    ]
