# Generated by Django 6.0.2 on 2026-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destekturu', '0003_oncelik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncelik',
            name='kod',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
