# Generated by Django 6.0.2 on 2026-02-22 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='program',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bolum',
            name='programresim',
            field=models.ImageField(blank=True, null=True, upload_to='resimler'),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='isim',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='kod',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='danisman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=10)),
                ('bolumkod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.bolum', to_field='kod')),
            ],
        ),
    ]
