# Generated by Django 6.0.2 on 2026-02-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0002_bolum_program_bolum_programresim_alter_bolum_isim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danisman',
            name='bolumkod',
        ),
    ]
