# Generated by Django 6.0.2 on 2026-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0003_remove_danisman_bolumkod'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisman',
            name='yetkinlik',
            field=models.ManyToManyField(blank=True, related_name='yetkinlikler', to='modul.bolum'),
        ),
    ]
