# Generated by Django 6.0.2 on 2026-02-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0004_danisman_yetkinlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisman',
            name='yetkinlik',
            field=models.ManyToManyField(related_name='yetkinlikler', to='modul.bolum'),
        ),
    ]
