# Generated by Django 6.0.2 on 2026-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0005_alter_danisman_yetkinlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisman',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
