# Generated by Django 6.0.3 on 2026-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_alter_danisman_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisman',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='danisman',
            name='tur',
            field=models.CharField(choices=[('İç Kaynak', 'İç Kaynak'), ('Dış Kaynak', 'Dış Kaynak')], default='İç Kaynak', max_length=20, verbose_name='Danışman Türü'),
        ),
    ]
