# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0007_danisman_email_danisman_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='yazilim_eforuna_dahil',
            field=models.BooleanField(default=False),
        ),
    ]
