# Generated by Django 6.0.2 on 2026-02-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0002_hesapgrubu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesapgrubu',
            name='grupkod',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='muhatap',
            name='vkn',
            field=models.CharField(max_length=11),
        ),
    ]
