# Generated by Django 6.0.2 on 2026-02-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0003_alter_hesapgrubu_grupkod_alter_muhatap_vkn'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhatap',
            name='grupkod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='muhatap.hesapgrubu', to_field='grupkod'),
        ),
    ]
