# Generated by Django 6.0.2 on 2026-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0004_muhatap_grupkod'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhatap',
            name='telefon',
            field=models.IntegerField(null=True, verbose_name=10),
        ),
    ]
