# Generated by Django 6.0.2 on 2026-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0005_muhatap_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhatap',
            name='telefon',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
