# Generated by Django 6.0.2 on 2026-02-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0006_alter_muhatap_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muhatap',
            name='unvan',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
