# Generated by Django 6.0.2 on 2026-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0007_alter_muhatap_unvan'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhatap',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
