# Generated by Django 6.0.2 on 2026-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0008_muhatap_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muhatap',
            name='slug',
        ),
        migrations.AddField(
            model_name='muhatap',
            name='aktif',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
