# Generated by Django 6.0.2 on 2026-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhatap', '0009_remove_muhatap_slug_muhatap_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='muhatap',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
