# Generated by Django 6.0.3 on 2026-05-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sozlesme', '0006_projelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='projeler',
            fields=[
                ('projeno', models.IntegerField(primary_key=True, serialize=False)),
                ('sozlesme_baglantisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sozlesme.sozlesmeler', to_field='sozlesmeno', verbose_name='İlgili Sözleşme')),
            ],
        ),
    ]
