# Generated by Django 6.0.3 on 2026-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='tanim',
            field=models.TextField(blank=True, null=True, verbose_name='Proje Tanımı'),
        ),
    ]
