# Generated by Django 6.0.3 on 2026-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0002_projeler_tanim'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Proje Açıklaması'),
        ),
        migrations.AlterField(
            model_name='projeler',
            name='tanim',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proje Tanımı'),
        ),
    ]
