# Generated by Django 6.0.3 on 2026-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departman',
            old_name='departman_name',
            new_name='tanim',
        ),
        migrations.RemoveField(
            model_name='departman',
            name='departman_kod',
        ),
        migrations.AddField(
            model_name='departman',
            name='kod',
            field=models.CharField(default='000', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
