# Generated by Django 6.0.2 on 2026-02-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muhatap', '0007_alter_muhatap_unvan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticketno', models.IntegerField(primary_key=True, serialize=False)),
                ('konu', models.CharField(max_length=100)),
                ('unvan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='muhatap.muhatap', to_field='unvan')),
            ],
        ),
    ]
