# Generated by Django 6.0.2 on 2026-02-21 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destekturu', '0002_alter_destektur_definition'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destekturu.destektur', to_field='definition'),
        ),
    ]
