# Generated by Django 6.0.2 on 2026-02-21 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0001_initial'),
        ('ticket', '0002_ticket_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bolumkod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.bolum', to_field='kod'),
        ),
    ]
