# Generated by Django 6.0.2 on 2026-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_bolumkod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='definition',
            new_name='destekturu',
        ),
    ]
