# Generated by Django 6.0.2 on 2026-02-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_definition_ticket_destekturu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='taleptarih',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='termintarih',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
