# Generated by Django 6.0.2 on 2026-02-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_taleptarih_ticket_termintarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketno',
            field=models.IntegerField(auto_created=True),
        ),
    ]
