# Generated by Django 6.0.2 on 2026-02-22 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destekturu', '0004_alter_oncelik_kod'),
        ('ticket', '0007_remove_ticket_id_alter_ticket_taleptarih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='oncelikkod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destekturu.oncelik', to_field='kod'),
        ),
    ]
