# Generated by Django 6.0.2 on 2026-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket_oncelikkod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
