# Generated by Django 6.0.2 on 2026-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketno',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
