# Generated by Django 6.0.2 on 2026-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticket_ticketno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketno',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
