# Generated by Django 6.0.2 on 2026-02-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticket_ticketno'),
    ]

    operations = [
        migrations.CreateModel(
            name='statu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durumtanim', models.CharField(max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='statu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.statu', to_field='durumtanim'),
        ),
    ]
