# Generated by Django 6.0.2 on 2026-02-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_statu_ticket_statu'),
    ]

    operations = [
        migrations.CreateModel(
            name='faturalama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturadurum', models.CharField(max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='statu',
            new_name='durumtanim',
        ),
        migrations.AddField(
            model_name='ticket',
            name='faturadurum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.faturalama', to_field='faturadurum'),
        ),
    ]
