# Generated by Django 6.0.2 on 2026-02-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_alter_danisman_username'),
        ('ticket', '0013_faturalama_rename_statu_ticket_durumtanim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danisman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.danisman', to_field='username')),
                ('ticketno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
    ]
