# Generated by Django 6.0.2 on 2026-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_atama'),
    ]

    operations = [
        migrations.AddField(
            model_name='atama',
            name='efor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atama',
            name='onay',
            field=models.BooleanField(default=False),
        ),
    ]
