# Generated by Django 6.0.2 on 2026-03-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_alter_danisman_username'),
        ('ticket', '0015_atama_efor_atama_onay'),
    ]

    operations = [
        migrations.AddField(
            model_name='atama',
            name='modul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.bolum', to_field='kod'),
        ),
    ]
