# Generated by Django 6.0.2 on 2026-03-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_alter_danisman_username'),
        ('ticket', '0016_atama_modul'),
    ]

    operations = [
        migrations.CreateModel(
            name='aktivite',
            fields=[
                ('number', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('saat', models.IntegerField(blank=True)),
                ('danisman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.danisman', to_field='username')),
                ('modul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.bolum', to_field='kod')),
                ('ticketno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
    ]
