# Generated by Django 6.0.2 on 2026-03-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_aktivite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aktivite',
            old_name='saat',
            new_name='time',
        ),
    ]
