# Generated by Django 6.0.2 on 2026-03-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlesme', '0005_sozlesmeler_aciklama'),
        ('ticket', '0018_rename_saat_aktivite_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sozlesmeno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sozlesme.sozlesmeler', to_field='sozlesmeno'),
        ),
    ]
