# Generated by Django 6.0.3 on 2026-05-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_alter_danisman_username'),
        ('ticket', '0019_ticket_sozlesmeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='danisman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modul.danisman', to_field='username'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='efor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='onay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aktivite',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
