# Generated by Django 6.0.3 on 2026-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_ticket_danisman_ticket_efor_ticket_onay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='musteri_ticket_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Müşteri Ticket No'),
        ),
    ]
