# Generated by Django 6.0.3 on 2026-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0007_danisman_email_danisman_tur'),
        ('ticket', '0021_ticket_musteri_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='danismanlar',
            field=models.ManyToManyField(blank=True, related_name='ticket_danismanlar', to='modul.danisman'),
        ),
    ]
