# Generated by Django 6.0.3 on 2026-05-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destekturu', '0004_alter_oncelik_kod'),
        ('ticket', '0024_remove_fk_rename_m2m_danisman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='destekturu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='destekturu.destektur', to_field='definition'),
        ),
    ]
