# Generated by Django 6.0.5 on 2026-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_alter_ticket_destekturu'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivite',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
