# Generated by Django 6.0.3 on 2026-05-25 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_aktivite_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='taleptarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
