# Generated by Django 6.0.3 on 2026-06-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_ticketyazisma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketyazisma',
            name='ticketno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazismalar', to='ticket.ticket'),
        ),
    ]
