# Generated by Codex on 2026-06-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departman', '0002_rename_departman_name_departman_tanim_and_more'),
        ('ticket', '0029_alter_ticketyazisma_ticketno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departmankod',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='departman.departman',
                to_field='kod',
            ),
        ),
    ]
