# Generated by Django 6.0.3 on 2026-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_ticket_departmankod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketyazisma',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='ticket_yazisma_dosyalari/'),
        ),
    ]
